# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "go-ext"
  path         = "go/ext"
}

created_at    = "2026-05-23T16:54:41.902973Z"
last_synced   = "2026-05-23T16:54:41.902973Z"
forge_version = "0.7.0"

variables {
  license             = "Apache-2.0"
  project_description = "Server Price Tracker"
  project_name        = "spt"
  project_owner       = "donaldgifford"
}

default ".checkmake.ini" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:123f1dc4a0f6e608cd57546d72894791ef719ad07cc0fdd53016d57557cb9284"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e1c704813a7cd6eccc0f86f4aa706f279270a1563360059fc706d81a02b38e3b"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/labeler.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:022ba7cb66a35028e3930d0477233dca98cfec611ac5698670e5e93b0396a3bf"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9d0bbe7ec5e56ac192a21ed557d5dc700375c60b555a874bc22c05eb57bd86d4"
}

default ".makefmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:c56b8f4be0b7722a0e8fda97faf4d8c29e4ff75193acf663bf5a5b0e7fbf4808"
}

default ".markdownlint.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:dc9182bd0b399616bd2b6933eb4b2a756674cedb43dbea914cf61f9180e3fc92"
}

default ".prettierrc.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:402823be7f1d14a6bdd7a8801c6392f7b8e74675e842aa355fccc07766b538d8"
}

default ".yamlfmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d214a4f56043cad5e01bd70e3530155df3bf7372bd2571aba87bcee0c1dcca73"
}

default ".yamllint.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:3f8575b37ea4a59395110326535d36573208fc6495ac47e357512fa7b8bbf7a9"
}

default ".codecov.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:6081acf89a7356486744ea90ddaa3daf20dba822209170e00392c255b6cbc7b4"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8d5a2d594e5f08f6b57a814830c9511b1c3c6cb3d1341bc5295e2638f20bd884"
}

default ".github/dependabot.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:46bf2769823e50c3bcf263246c146eca1bf5e785f907fe5308a2aab902039cca"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4671b90741cc743c3b6bc8d9b6fe132dd1ad4bb2599344c9ebcb2ae62368c106"
}

default ".golangci.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7a0182968406bfbb8ca6031b4d53bc319e9718e7c53912aad6e18a0d0ba2acce"
}

default ".goreleaser.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8a05eaa844c8c17b7ee41da3cf5f0e4fbccd7c384ac7e0a72c11ce0241a535c6"
}

default "Makefile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:076169d0f498ac9bb4409870a64abf36c9e2c17bec9685e3855806e5585c5afd"
}

default "cmd/$${project_name}/main.go.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
}

default "justfile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:89a1d1426cf7762704ac69b0385455c34ef423a408f6c4cc3a03f2a292b28091"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:37dead1ff5c5babd978afa02f4a8ac0ddd24396378b6f12cfeb808085accdcb8"
}
