---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spt
  title: Server Price Tracker
  description: "Agentic Server Price Tracker"
  annotations:
    backstage.io/code-coverage: enabled
    backstage.io/source-location: url:https://github.com/donaldgifford/spt
    backstage.io/techdocs-ref: "dir:."
    github.com/project-slug: "donaldgifford/spt"
    jira/label: "spt"
  tags:
    - go
    - github
  namespace: default
spec:
  lifecycle: production
  type: service
  owner: homelab
  system: applicaitons
