// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/domain"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// CancelJob provides a mock function for the type MockScheduler
func (_mock *MockScheduler) CancelJob(ctx context.Context, id domain.JobID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.JobID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockScheduler_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.JobID
func (_e *MockScheduler_Expecter) CancelJob(ctx interface{}, id interface{}) *MockScheduler_CancelJob_Call {
	return &MockScheduler_CancelJob_Call{Call: _e.mock.On("CancelJob", ctx, id)}
}

func (_c *MockScheduler_CancelJob_Call) Run(run func(ctx context.Context, id domain.JobID)) *MockScheduler_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.JobID
		if args[1] != nil {
			arg1 = args[1].(domain.JobID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_CancelJob_Call) Return(err error) *MockScheduler_CancelJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_CancelJob_Call) RunAndReturn(run func(ctx context.Context, id domain.JobID) error) *MockScheduler_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockScheduler
func (_mock *MockScheduler) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockScheduler_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScheduler_Expecter) Run(ctx interface{}) *MockScheduler_Run_Call {
	return &MockScheduler_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockScheduler_Run_Call) Run(run func(ctx context.Context)) *MockScheduler_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_Run_Call) Return(err error) *MockScheduler_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_Run_Call) RunAndReturn(run func(ctx context.Context) error) *MockScheduler_Run_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerWatch provides a mock function for the type MockScheduler
func (_mock *MockScheduler) TriggerWatch(ctx context.Context, id domain.WatchID, trigger domain.JobTrigger) (domain.JobID, error) {
	ret := _mock.Called(ctx, id, trigger)

	if len(ret) == 0 {
		panic("no return value specified for TriggerWatch")
	}

	var r0 domain.JobID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WatchID, domain.JobTrigger) (domain.JobID, error)); ok {
		return returnFunc(ctx, id, trigger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WatchID, domain.JobTrigger) domain.JobID); ok {
		r0 = returnFunc(ctx, id, trigger)
	} else {
		r0 = ret.Get(0).(domain.JobID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.WatchID, domain.JobTrigger) error); ok {
		r1 = returnFunc(ctx, id, trigger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduler_TriggerWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerWatch'
type MockScheduler_TriggerWatch_Call struct {
	*mock.Call
}

// TriggerWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.WatchID
//   - trigger domain.JobTrigger
func (_e *MockScheduler_Expecter) TriggerWatch(ctx interface{}, id interface{}, trigger interface{}) *MockScheduler_TriggerWatch_Call {
	return &MockScheduler_TriggerWatch_Call{Call: _e.mock.On("TriggerWatch", ctx, id, trigger)}
}

func (_c *MockScheduler_TriggerWatch_Call) Run(run func(ctx context.Context, id domain.WatchID, trigger domain.JobTrigger)) *MockScheduler_TriggerWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.WatchID
		if args[1] != nil {
			arg1 = args[1].(domain.WatchID)
		}
		var arg2 domain.JobTrigger
		if args[2] != nil {
			arg2 = args[2].(domain.JobTrigger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScheduler_TriggerWatch_Call) Return(jobID domain.JobID, err error) *MockScheduler_TriggerWatch_Call {
	_c.Call.Return(jobID, err)
	return _c
}

func (_c *MockScheduler_TriggerWatch_Call) RunAndReturn(run func(ctx context.Context, id domain.WatchID, trigger domain.JobTrigger) (domain.JobID, error)) *MockScheduler_TriggerWatch_Call {
	_c.Call.Return(run)
	return _c
}
