package cli

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// disableAutoGenTag flips DisableAutoGenTag on cmd and every nested
// subcommand so doc.GenMarkdownTree omits the daily-rotating footer.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

// newDocsCmd returns the hidden `gen-docs <output-dir>` subcommand
// used by the docgen workflow (`just docs-cli`). The implementation is
// one call into spf13/cobra/doc — too small to justify its own tool
// binary under tools/ (see IMPL-0002 Phase 2 and DESIGN-0006 "docgen").
//
// Hidden:true keeps the command out of `spt --help`; it's a maintainer
// tool, not part of the operator surface.
func newDocsCmd() *cobra.Command {
	return &cobra.Command{
		Use:    "gen-docs <output-dir>",
		Short:  "Regenerate the docs/cli/ markdown tree from the live command set",
		Hidden: true,
		Args:   cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			root := cmd.Root()
			// Disable the auto-generated "Auto generated by spf13/cobra
			// on DD-Mon-YYYY" footer — it rotates daily and would
			// time-bomb the drift check. Apply recursively so every
			// subcommand's page skips the footer too.
			disableAutoGenTag(root)
			if err := doc.GenMarkdownTree(root, args[0]); err != nil {
				return fmt.Errorf("cli: gen-docs: %w", err)
			}
			return nil
		},
	}
}
