// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/domain"
	"github.com/donaldgifford/spt/internal/queue"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockQueue
func (_mock *MockQueue) Ack(ctx context.Context, id domain.TaskID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockQueue_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TaskID
func (_e *MockQueue_Expecter) Ack(ctx interface{}, id interface{}) *MockQueue_Ack_Call {
	return &MockQueue_Ack_Call{Call: _e.mock.On("Ack", ctx, id)}
}

func (_c *MockQueue_Ack_Call) Run(run func(ctx context.Context, id domain.TaskID)) *MockQueue_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskID
		if args[1] != nil {
			arg1 = args[1].(domain.TaskID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Ack_Call) Return(err error) *MockQueue_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Ack_Call) RunAndReturn(run func(ctx context.Context, id domain.TaskID) error) *MockQueue_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Dequeue provides a mock function for the type MockQueue
func (_mock *MockQueue) Dequeue(ctx context.Context, stages []domain.Stage) (domain.Task, error) {
	ret := _mock.Called(ctx, stages)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Stage) (domain.Task, error)); ok {
		return returnFunc(ctx, stages)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Stage) domain.Task); ok {
		r0 = returnFunc(ctx, stages)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.Stage) error); ok {
		r1 = returnFunc(ctx, stages)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type MockQueue_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - stages []domain.Stage
func (_e *MockQueue_Expecter) Dequeue(ctx interface{}, stages interface{}) *MockQueue_Dequeue_Call {
	return &MockQueue_Dequeue_Call{Call: _e.mock.On("Dequeue", ctx, stages)}
}

func (_c *MockQueue_Dequeue_Call) Run(run func(ctx context.Context, stages []domain.Stage)) *MockQueue_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Stage
		if args[1] != nil {
			arg1 = args[1].([]domain.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Dequeue_Call) Return(task domain.Task, err error) *MockQueue_Dequeue_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockQueue_Dequeue_Call) RunAndReturn(run func(ctx context.Context, stages []domain.Stage) (domain.Task, error)) *MockQueue_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockQueue
func (_mock *MockQueue) Enqueue(ctx context.Context, task domain.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockQueue_Expecter) Enqueue(ctx interface{}, task interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, task)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, task domain.Task)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(err error) *MockQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) error) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Nack provides a mock function for the type MockQueue
func (_mock *MockQueue) Nack(ctx context.Context, id domain.TaskID, retryAfter time.Duration) error {
	ret := _mock.Called(ctx, id, retryAfter)

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskID, time.Duration) error); ok {
		r0 = returnFunc(ctx, id, retryAfter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Nack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nack'
type MockQueue_Nack_Call struct {
	*mock.Call
}

// Nack is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TaskID
//   - retryAfter time.Duration
func (_e *MockQueue_Expecter) Nack(ctx interface{}, id interface{}, retryAfter interface{}) *MockQueue_Nack_Call {
	return &MockQueue_Nack_Call{Call: _e.mock.On("Nack", ctx, id, retryAfter)}
}

func (_c *MockQueue_Nack_Call) Run(run func(ctx context.Context, id domain.TaskID, retryAfter time.Duration)) *MockQueue_Nack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskID
		if args[1] != nil {
			arg1 = args[1].(domain.TaskID)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Nack_Call) Return(err error) *MockQueue_Nack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Nack_Call) RunAndReturn(run func(ctx context.Context, id domain.TaskID, retryAfter time.Duration) error) *MockQueue_Nack_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockQueue
func (_mock *MockQueue) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockQueue_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueue_Expecter) Ping(ctx interface{}) *MockQueue_Ping_Call {
	return &MockQueue_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockQueue_Ping_Call) Run(run func(ctx context.Context)) *MockQueue_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueue_Ping_Call) Return(err error) *MockQueue_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockQueue_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// QueueDepth provides a mock function for the type MockQueue
func (_mock *MockQueue) QueueDepth(ctx context.Context, stage domain.Stage) (int64, error) {
	ret := _mock.Called(ctx, stage)

	if len(ret) == 0 {
		panic("no return value specified for QueueDepth")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Stage) (int64, error)); ok {
		return returnFunc(ctx, stage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Stage) int64); ok {
		r0 = returnFunc(ctx, stage)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Stage) error); ok {
		r1 = returnFunc(ctx, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_QueueDepth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueDepth'
type MockQueue_QueueDepth_Call struct {
	*mock.Call
}

// QueueDepth is a helper method to define mock.On call
//   - ctx context.Context
//   - stage domain.Stage
func (_e *MockQueue_Expecter) QueueDepth(ctx interface{}, stage interface{}) *MockQueue_QueueDepth_Call {
	return &MockQueue_QueueDepth_Call{Call: _e.mock.On("QueueDepth", ctx, stage)}
}

func (_c *MockQueue_QueueDepth_Call) Run(run func(ctx context.Context, stage domain.Stage)) *MockQueue_QueueDepth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Stage
		if args[1] != nil {
			arg1 = args[1].(domain.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_QueueDepth_Call) Return(n int64, err error) *MockQueue_QueueDepth_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueue_QueueDepth_Call) RunAndReturn(run func(ctx context.Context, stage domain.Stage) (int64, error)) *MockQueue_QueueDepth_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockQueue
func (_mock *MockQueue) Subscribe(ctx context.Context, channel string) (<-chan queue.QueueEvent, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan queue.QueueEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (<-chan queue.QueueEvent, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan queue.QueueEvent); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan queue.QueueEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockQueue_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
func (_e *MockQueue_Expecter) Subscribe(ctx interface{}, channel interface{}) *MockQueue_Subscribe_Call {
	return &MockQueue_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, channel)}
}

func (_c *MockQueue_Subscribe_Call) Run(run func(ctx context.Context, channel string)) *MockQueue_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Subscribe_Call) Return(queueEventCh <-chan queue.QueueEvent, err error) *MockQueue_Subscribe_Call {
	_c.Call.Return(queueEventCh, err)
	return _c
}

func (_c *MockQueue_Subscribe_Call) RunAndReturn(run func(ctx context.Context, channel string) (<-chan queue.QueueEvent, error)) *MockQueue_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
