// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/datastore"
	"github.com/donaldgifford/spt/internal/domain"
)

// NewMockDatastore creates a new instance of MockDatastore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastore {
	mock := &MockDatastore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatastore is an autogenerated mock type for the Datastore type
type MockDatastore struct {
	mock.Mock
}

type MockDatastore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastore) EXPECT() *MockDatastore_Expecter {
	return &MockDatastore_Expecter{mock: &_m.Mock}
}

// CreateJob provides a mock function for the type MockDatastore
func (_mock *MockDatastore) CreateJob(ctx context.Context, j domain.Job) error {
	ret := _mock.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Job) error); ok {
		r0 = returnFunc(ctx, j)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockDatastore_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - j domain.Job
func (_e *MockDatastore_Expecter) CreateJob(ctx interface{}, j interface{}) *MockDatastore_CreateJob_Call {
	return &MockDatastore_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, j)}
}

func (_c *MockDatastore_CreateJob_Call) Run(run func(ctx context.Context, j domain.Job)) *MockDatastore_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_CreateJob_Call) Return(err error) *MockDatastore_CreateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_CreateJob_Call) RunAndReturn(run func(ctx context.Context, j domain.Job) error) *MockDatastore_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// DueWatches provides a mock function for the type MockDatastore
func (_mock *MockDatastore) DueWatches(ctx context.Context, now time.Time, limit int) ([]domain.Watch, error) {
	ret := _mock.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for DueWatches")
	}

	var r0 []domain.Watch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]domain.Watch, error)); ok {
		return returnFunc(ctx, now, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []domain.Watch); ok {
		r0 = returnFunc(ctx, now, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Watch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_DueWatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DueWatches'
type MockDatastore_DueWatches_Call struct {
	*mock.Call
}

// DueWatches is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int
func (_e *MockDatastore_Expecter) DueWatches(ctx interface{}, now interface{}, limit interface{}) *MockDatastore_DueWatches_Call {
	return &MockDatastore_DueWatches_Call{Call: _e.mock.On("DueWatches", ctx, now, limit)}
}

func (_c *MockDatastore_DueWatches_Call) Run(run func(ctx context.Context, now time.Time, limit int)) *MockDatastore_DueWatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastore_DueWatches_Call) Return(watchs []domain.Watch, err error) *MockDatastore_DueWatches_Call {
	_c.Call.Return(watchs, err)
	return _c
}

func (_c *MockDatastore_DueWatches_Call) RunAndReturn(run func(ctx context.Context, now time.Time, limit int) ([]domain.Watch, error)) *MockDatastore_DueWatches_Call {
	_c.Call.Return(run)
	return _c
}

// GetListing provides a mock function for the type MockDatastore
func (_mock *MockDatastore) GetListing(ctx context.Context, id domain.ListingID) (domain.Listing, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetListing")
	}

	var r0 domain.Listing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListingID) (domain.Listing, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListingID) domain.Listing); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Listing)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListingID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_GetListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListing'
type MockDatastore_GetListing_Call struct {
	*mock.Call
}

// GetListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ListingID
func (_e *MockDatastore_Expecter) GetListing(ctx interface{}, id interface{}) *MockDatastore_GetListing_Call {
	return &MockDatastore_GetListing_Call{Call: _e.mock.On("GetListing", ctx, id)}
}

func (_c *MockDatastore_GetListing_Call) Run(run func(ctx context.Context, id domain.ListingID)) *MockDatastore_GetListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListingID
		if args[1] != nil {
			arg1 = args[1].(domain.ListingID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_GetListing_Call) Return(listing domain.Listing, err error) *MockDatastore_GetListing_Call {
	_c.Call.Return(listing, err)
	return _c
}

func (_c *MockDatastore_GetListing_Call) RunAndReturn(run func(ctx context.Context, id domain.ListingID) (domain.Listing, error)) *MockDatastore_GetListing_Call {
	_c.Call.Return(run)
	return _c
}

// GetListingByEbayItemID provides a mock function for the type MockDatastore
func (_mock *MockDatastore) GetListingByEbayItemID(ctx context.Context, ebayID string) (domain.Listing, error) {
	ret := _mock.Called(ctx, ebayID)

	if len(ret) == 0 {
		panic("no return value specified for GetListingByEbayItemID")
	}

	var r0 domain.Listing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Listing, error)); ok {
		return returnFunc(ctx, ebayID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Listing); ok {
		r0 = returnFunc(ctx, ebayID)
	} else {
		r0 = ret.Get(0).(domain.Listing)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ebayID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_GetListingByEbayItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListingByEbayItemID'
type MockDatastore_GetListingByEbayItemID_Call struct {
	*mock.Call
}

// GetListingByEbayItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - ebayID string
func (_e *MockDatastore_Expecter) GetListingByEbayItemID(ctx interface{}, ebayID interface{}) *MockDatastore_GetListingByEbayItemID_Call {
	return &MockDatastore_GetListingByEbayItemID_Call{Call: _e.mock.On("GetListingByEbayItemID", ctx, ebayID)}
}

func (_c *MockDatastore_GetListingByEbayItemID_Call) Run(run func(ctx context.Context, ebayID string)) *MockDatastore_GetListingByEbayItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_GetListingByEbayItemID_Call) Return(listing domain.Listing, err error) *MockDatastore_GetListingByEbayItemID_Call {
	_c.Call.Return(listing, err)
	return _c
}

func (_c *MockDatastore_GetListingByEbayItemID_Call) RunAndReturn(run func(ctx context.Context, ebayID string) (domain.Listing, error)) *MockDatastore_GetListingByEbayItemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWatch provides a mock function for the type MockDatastore
func (_mock *MockDatastore) GetWatch(ctx context.Context, id domain.WatchID) (domain.Watch, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWatch")
	}

	var r0 domain.Watch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WatchID) (domain.Watch, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WatchID) domain.Watch); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Watch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.WatchID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_GetWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWatch'
type MockDatastore_GetWatch_Call struct {
	*mock.Call
}

// GetWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.WatchID
func (_e *MockDatastore_Expecter) GetWatch(ctx interface{}, id interface{}) *MockDatastore_GetWatch_Call {
	return &MockDatastore_GetWatch_Call{Call: _e.mock.On("GetWatch", ctx, id)}
}

func (_c *MockDatastore_GetWatch_Call) Run(run func(ctx context.Context, id domain.WatchID)) *MockDatastore_GetWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.WatchID
		if args[1] != nil {
			arg1 = args[1].(domain.WatchID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_GetWatch_Call) Return(watch domain.Watch, err error) *MockDatastore_GetWatch_Call {
	_c.Call.Return(watch, err)
	return _c
}

func (_c *MockDatastore_GetWatch_Call) RunAndReturn(run func(ctx context.Context, id domain.WatchID) (domain.Watch, error)) *MockDatastore_GetWatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListWatches provides a mock function for the type MockDatastore
func (_mock *MockDatastore) ListWatches(ctx context.Context, f datastore.WatchFilter) ([]domain.Watch, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListWatches")
	}

	var r0 []domain.Watch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.WatchFilter) ([]domain.Watch, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.WatchFilter) []domain.Watch); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Watch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, datastore.WatchFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_ListWatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWatches'
type MockDatastore_ListWatches_Call struct {
	*mock.Call
}

// ListWatches is a helper method to define mock.On call
//   - ctx context.Context
//   - f datastore.WatchFilter
func (_e *MockDatastore_Expecter) ListWatches(ctx interface{}, f interface{}) *MockDatastore_ListWatches_Call {
	return &MockDatastore_ListWatches_Call{Call: _e.mock.On("ListWatches", ctx, f)}
}

func (_c *MockDatastore_ListWatches_Call) Run(run func(ctx context.Context, f datastore.WatchFilter)) *MockDatastore_ListWatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.WatchFilter
		if args[1] != nil {
			arg1 = args[1].(datastore.WatchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_ListWatches_Call) Return(watchs []domain.Watch, err error) *MockDatastore_ListWatches_Call {
	_c.Call.Return(watchs, err)
	return _c
}

func (_c *MockDatastore_ListWatches_Call) RunAndReturn(run func(ctx context.Context, f datastore.WatchFilter) ([]domain.Watch, error)) *MockDatastore_ListWatches_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDatastore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatastore_Expecter) Ping(ctx interface{}) *MockDatastore_Ping_Call {
	return &MockDatastore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDatastore_Ping_Call) Run(run func(ctx context.Context)) *MockDatastore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatastore_Ping_Call) Return(err error) *MockDatastore_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockDatastore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceComponents provides a mock function for the type MockDatastore
func (_mock *MockDatastore) ReplaceComponents(ctx context.Context, listingID domain.ListingID, components []domain.Component) error {
	ret := _mock.Called(ctx, listingID, components)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceComponents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListingID, []domain.Component) error); ok {
		r0 = returnFunc(ctx, listingID, components)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_ReplaceComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceComponents'
type MockDatastore_ReplaceComponents_Call struct {
	*mock.Call
}

// ReplaceComponents is a helper method to define mock.On call
//   - ctx context.Context
//   - listingID domain.ListingID
//   - components []domain.Component
func (_e *MockDatastore_Expecter) ReplaceComponents(ctx interface{}, listingID interface{}, components interface{}) *MockDatastore_ReplaceComponents_Call {
	return &MockDatastore_ReplaceComponents_Call{Call: _e.mock.On("ReplaceComponents", ctx, listingID, components)}
}

func (_c *MockDatastore_ReplaceComponents_Call) Run(run func(ctx context.Context, listingID domain.ListingID, components []domain.Component)) *MockDatastore_ReplaceComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListingID
		if args[1] != nil {
			arg1 = args[1].(domain.ListingID)
		}
		var arg2 []domain.Component
		if args[2] != nil {
			arg2 = args[2].([]domain.Component)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastore_ReplaceComponents_Call) Return(err error) *MockDatastore_ReplaceComponents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_ReplaceComponents_Call) RunAndReturn(run func(ctx context.Context, listingID domain.ListingID, components []domain.Component) error) *MockDatastore_ReplaceComponents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobState provides a mock function for the type MockDatastore
func (_mock *MockDatastore) UpdateJobState(ctx context.Context, id domain.JobID, state domain.JobState) error {
	ret := _mock.Called(ctx, id, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.JobID, domain.JobState) error); ok {
		r0 = returnFunc(ctx, id, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_UpdateJobState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobState'
type MockDatastore_UpdateJobState_Call struct {
	*mock.Call
}

// UpdateJobState is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.JobID
//   - state domain.JobState
func (_e *MockDatastore_Expecter) UpdateJobState(ctx interface{}, id interface{}, state interface{}) *MockDatastore_UpdateJobState_Call {
	return &MockDatastore_UpdateJobState_Call{Call: _e.mock.On("UpdateJobState", ctx, id, state)}
}

func (_c *MockDatastore_UpdateJobState_Call) Run(run func(ctx context.Context, id domain.JobID, state domain.JobState)) *MockDatastore_UpdateJobState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.JobID
		if args[1] != nil {
			arg1 = args[1].(domain.JobID)
		}
		var arg2 domain.JobState
		if args[2] != nil {
			arg2 = args[2].(domain.JobState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastore_UpdateJobState_Call) Return(err error) *MockDatastore_UpdateJobState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_UpdateJobState_Call) RunAndReturn(run func(ctx context.Context, id domain.JobID, state domain.JobState) error) *MockDatastore_UpdateJobState_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertListing provides a mock function for the type MockDatastore
func (_mock *MockDatastore) UpsertListing(ctx context.Context, l domain.Listing) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for UpsertListing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Listing) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_UpsertListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertListing'
type MockDatastore_UpsertListing_Call struct {
	*mock.Call
}

// UpsertListing is a helper method to define mock.On call
//   - ctx context.Context
//   - l domain.Listing
func (_e *MockDatastore_Expecter) UpsertListing(ctx interface{}, l interface{}) *MockDatastore_UpsertListing_Call {
	return &MockDatastore_UpsertListing_Call{Call: _e.mock.On("UpsertListing", ctx, l)}
}

func (_c *MockDatastore_UpsertListing_Call) Run(run func(ctx context.Context, l domain.Listing)) *MockDatastore_UpsertListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Listing
		if args[1] != nil {
			arg1 = args[1].(domain.Listing)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_UpsertListing_Call) Return(err error) *MockDatastore_UpsertListing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_UpsertListing_Call) RunAndReturn(run func(ctx context.Context, l domain.Listing) error) *MockDatastore_UpsertListing_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTask provides a mock function for the type MockDatastore
func (_mock *MockDatastore) UpsertTask(ctx context.Context, t domain.Task) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_UpsertTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTask'
type MockDatastore_UpsertTask_Call struct {
	*mock.Call
}

// UpsertTask is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.Task
func (_e *MockDatastore_Expecter) UpsertTask(ctx interface{}, t interface{}) *MockDatastore_UpsertTask_Call {
	return &MockDatastore_UpsertTask_Call{Call: _e.mock.On("UpsertTask", ctx, t)}
}

func (_c *MockDatastore_UpsertTask_Call) Run(run func(ctx context.Context, t domain.Task)) *MockDatastore_UpsertTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_UpsertTask_Call) Return(err error) *MockDatastore_UpsertTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_UpsertTask_Call) RunAndReturn(run func(ctx context.Context, t domain.Task) error) *MockDatastore_UpsertTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertWatch provides a mock function for the type MockDatastore
func (_mock *MockDatastore) UpsertWatch(ctx context.Context, w domain.Watch) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Watch) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_UpsertWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWatch'
type MockDatastore_UpsertWatch_Call struct {
	*mock.Call
}

// UpsertWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - w domain.Watch
func (_e *MockDatastore_Expecter) UpsertWatch(ctx interface{}, w interface{}) *MockDatastore_UpsertWatch_Call {
	return &MockDatastore_UpsertWatch_Call{Call: _e.mock.On("UpsertWatch", ctx, w)}
}

func (_c *MockDatastore_UpsertWatch_Call) Run(run func(ctx context.Context, w domain.Watch)) *MockDatastore_UpsertWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Watch
		if args[1] != nil {
			arg1 = args[1].(domain.Watch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_UpsertWatch_Call) Return(err error) *MockDatastore_UpsertWatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_UpsertWatch_Call) RunAndReturn(run func(ctx context.Context, w domain.Watch) error) *MockDatastore_UpsertWatch_Call {
	_c.Call.Return(run)
	return _c
}
