// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/agent"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockAgent
func (_mock *MockAgent) Complete(ctx context.Context, req agent.CompleteRequest) (agent.CompleteResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 agent.CompleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.CompleteRequest) (agent.CompleteResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.CompleteRequest) agent.CompleteResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(agent.CompleteResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, agent.CompleteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgent_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockAgent_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - req agent.CompleteRequest
func (_e *MockAgent_Expecter) Complete(ctx interface{}, req interface{}) *MockAgent_Complete_Call {
	return &MockAgent_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *MockAgent_Complete_Call) Run(run func(ctx context.Context, req agent.CompleteRequest)) *MockAgent_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 agent.CompleteRequest
		if args[1] != nil {
			arg1 = args[1].(agent.CompleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgent_Complete_Call) Return(completeResponse agent.CompleteResponse, err error) *MockAgent_Complete_Call {
	_c.Call.Return(completeResponse, err)
	return _c
}

func (_c *MockAgent_Complete_Call) RunAndReturn(run func(ctx context.Context, req agent.CompleteRequest) (agent.CompleteResponse, error)) *MockAgent_Complete_Call {
	_c.Call.Return(run)
	return _c
}
