// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/domain"
	"github.com/donaldgifford/spt/internal/search"
)

// NewMockSearch creates a new instance of MockSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearch {
	mock := &MockSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearch is an autogenerated mock type for the Search type
type MockSearch struct {
	mock.Mock
}

type MockSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearch) EXPECT() *MockSearch_Expecter {
	return &MockSearch_Expecter{mock: &_m.Mock}
}

// DeleteListing provides a mock function for the type MockSearch
func (_mock *MockSearch) DeleteListing(ctx context.Context, id domain.ListingID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteListing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListingID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSearch_DeleteListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteListing'
type MockSearch_DeleteListing_Call struct {
	*mock.Call
}

// DeleteListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ListingID
func (_e *MockSearch_Expecter) DeleteListing(ctx interface{}, id interface{}) *MockSearch_DeleteListing_Call {
	return &MockSearch_DeleteListing_Call{Call: _e.mock.On("DeleteListing", ctx, id)}
}

func (_c *MockSearch_DeleteListing_Call) Run(run func(ctx context.Context, id domain.ListingID)) *MockSearch_DeleteListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListingID
		if args[1] != nil {
			arg1 = args[1].(domain.ListingID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearch_DeleteListing_Call) Return(err error) *MockSearch_DeleteListing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSearch_DeleteListing_Call) RunAndReturn(run func(ctx context.Context, id domain.ListingID) error) *MockSearch_DeleteListing_Call {
	_c.Call.Return(run)
	return _c
}

// IndexListing provides a mock function for the type MockSearch
func (_mock *MockSearch) IndexListing(ctx context.Context, l domain.Listing) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for IndexListing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Listing) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSearch_IndexListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexListing'
type MockSearch_IndexListing_Call struct {
	*mock.Call
}

// IndexListing is a helper method to define mock.On call
//   - ctx context.Context
//   - l domain.Listing
func (_e *MockSearch_Expecter) IndexListing(ctx interface{}, l interface{}) *MockSearch_IndexListing_Call {
	return &MockSearch_IndexListing_Call{Call: _e.mock.On("IndexListing", ctx, l)}
}

func (_c *MockSearch_IndexListing_Call) Run(run func(ctx context.Context, l domain.Listing)) *MockSearch_IndexListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Listing
		if args[1] != nil {
			arg1 = args[1].(domain.Listing)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearch_IndexListing_Call) Return(err error) *MockSearch_IndexListing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSearch_IndexListing_Call) RunAndReturn(run func(ctx context.Context, l domain.Listing) error) *MockSearch_IndexListing_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockSearch
func (_mock *MockSearch) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSearch_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSearch_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSearch_Expecter) Ping(ctx interface{}) *MockSearch_Ping_Call {
	return &MockSearch_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockSearch_Ping_Call) Run(run func(ctx context.Context)) *MockSearch_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSearch_Ping_Call) Return(err error) *MockSearch_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSearch_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockSearch_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockSearch
func (_mock *MockSearch) Query(ctx context.Context, q search.Query) ([]domain.ListingID, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []domain.ListingID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.Query) ([]domain.ListingID, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.Query) []domain.ListingID); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ListingID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, search.Query) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearch_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSearch_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - q search.Query
func (_e *MockSearch_Expecter) Query(ctx interface{}, q interface{}) *MockSearch_Query_Call {
	return &MockSearch_Query_Call{Call: _e.mock.On("Query", ctx, q)}
}

func (_c *MockSearch_Query_Call) Run(run func(ctx context.Context, q search.Query)) *MockSearch_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 search.Query
		if args[1] != nil {
			arg1 = args[1].(search.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearch_Query_Call) Return(listingIDs []domain.ListingID, err error) *MockSearch_Query_Call {
	_c.Call.Return(listingIDs, err)
	return _c
}

func (_c *MockSearch_Query_Call) RunAndReturn(run func(ctx context.Context, q search.Query) ([]domain.ListingID, error)) *MockSearch_Query_Call {
	_c.Call.Return(run)
	return _c
}
