// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/ebay"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetItem provides a mock function for the type MockClient
func (_mock *MockClient) GetItem(ctx context.Context, ebayItemID string) (ebay.Item, error) {
	ret := _mock.Called(ctx, ebayItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 ebay.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ebay.Item, error)); ok {
		return returnFunc(ctx, ebayItemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ebay.Item); ok {
		r0 = returnFunc(ctx, ebayItemID)
	} else {
		r0 = ret.Get(0).(ebay.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ebayItemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockClient_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - ebayItemID string
func (_e *MockClient_Expecter) GetItem(ctx interface{}, ebayItemID interface{}) *MockClient_GetItem_Call {
	return &MockClient_GetItem_Call{Call: _e.mock.On("GetItem", ctx, ebayItemID)}
}

func (_c *MockClient_GetItem_Call) Run(run func(ctx context.Context, ebayItemID string)) *MockClient_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetItem_Call) Return(item ebay.Item, err error) *MockClient_GetItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockClient_GetItem_Call) RunAndReturn(run func(ctx context.Context, ebayItemID string) (ebay.Item, error)) *MockClient_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockClient
func (_mock *MockClient) Search(ctx context.Context, req ebay.SearchRequest) (ebay.SearchResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 ebay.SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ebay.SearchRequest) (ebay.SearchResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ebay.SearchRequest) ebay.SearchResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(ebay.SearchResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ebay.SearchRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req ebay.SearchRequest
func (_e *MockClient_Expecter) Search(ctx interface{}, req interface{}) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *MockClient_Search_Call) Run(run func(ctx context.Context, req ebay.SearchRequest)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ebay.SearchRequest
		if args[1] != nil {
			arg1 = args[1].(ebay.SearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(searchResponse ebay.SearchResponse, err error) *MockClient_Search_Call {
	_c.Call.Return(searchResponse, err)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(ctx context.Context, req ebay.SearchRequest) (ebay.SearchResponse, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}
