// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/spt/internal/ebay"
)

// NewMockRateLimiter creates a new instance of MockRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiter {
	mock := &MockRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

type MockRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiter) EXPECT() *MockRateLimiter_Expecter {
	return &MockRateLimiter_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function for the type MockRateLimiter
func (_mock *MockRateLimiter) Snapshot(ctx context.Context) (ebay.Snapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 ebay.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ebay.Snapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ebay.Snapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ebay.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRateLimiter_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockRateLimiter_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRateLimiter_Expecter) Snapshot(ctx interface{}) *MockRateLimiter_Snapshot_Call {
	return &MockRateLimiter_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx)}
}

func (_c *MockRateLimiter_Snapshot_Call) Run(run func(ctx context.Context)) *MockRateLimiter_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRateLimiter_Snapshot_Call) Return(snapshot ebay.Snapshot, err error) *MockRateLimiter_Snapshot_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockRateLimiter_Snapshot_Call) RunAndReturn(run func(ctx context.Context) (ebay.Snapshot, error)) *MockRateLimiter_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockRateLimiter
func (_mock *MockRateLimiter) Sync(ctx context.Context, count int64, limit int64, resetAt time.Time) error {
	ret := _mock.Called(ctx, count, limit, resetAt)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, count, limit, resetAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRateLimiter_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockRateLimiter_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - count int64
//   - limit int64
//   - resetAt time.Time
func (_e *MockRateLimiter_Expecter) Sync(ctx interface{}, count interface{}, limit interface{}, resetAt interface{}) *MockRateLimiter_Sync_Call {
	return &MockRateLimiter_Sync_Call{Call: _e.mock.On("Sync", ctx, count, limit, resetAt)}
}

func (_c *MockRateLimiter_Sync_Call) Run(run func(ctx context.Context, count int64, limit int64, resetAt time.Time)) *MockRateLimiter_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRateLimiter_Sync_Call) Return(err error) *MockRateLimiter_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRateLimiter_Sync_Call) RunAndReturn(run func(ctx context.Context, count int64, limit int64, resetAt time.Time) error) *MockRateLimiter_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockRateLimiter
func (_mock *MockRateLimiter) Wait(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRateLimiter_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockRateLimiter_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRateLimiter_Expecter) Wait(ctx interface{}) *MockRateLimiter_Wait_Call {
	return &MockRateLimiter_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockRateLimiter_Wait_Call) Run(run func(ctx context.Context)) *MockRateLimiter_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRateLimiter_Wait_Call) Return(err error) *MockRateLimiter_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRateLimiter_Wait_Call) RunAndReturn(run func(ctx context.Context) error) *MockRateLimiter_Wait_Call {
	_c.Call.Return(run)
	return _c
}
